name: mediator
description: "Simple, unambitious mediator implementation in Flutter"
version: 0.0.1
maintainer: Faraj Shuaib (@farajshuaib)
homepage: https://github.com/farajshuaib/flutter_mediator

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  glob: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.0.0
  build_runner: ^2.0.0
  source_gen: ^1.5.0

build:
source_gen:


flutter:


